### DISCUSSION TITLE
Docker installation

### DISCUSSION THREAD

**Discussion by LukanRocks** [kantorge/yaffa#259] [Q&A] [answered]
Hey! 👋

I'm no engineer, but I ended up getting into the self-hosting hobby with Home Assistant, and things grew from there. However, I got as far as knowing how to set up open-source projects using Docker Compose.

I saw this project being featured on https://github.com/awesome-selfhosted/awesome-selfhosted and got super interested, but the "get started" options to install are a bit beyond my knowledge.

Is there any way to spin a container image using docker?

**Comment by kantorge** [comment, marked as answer]
> Hey! 👋
> 
> I'm no engineer, but I ended up getting into the self-hosting hobby with Home Assistant, and things grew from there. However, I got as far as knowing how to set up open-source projects using Docker Compose.
> 
> I saw this project being featured on https://github.com/awesome-selfhosted/awesome-selfhosted and got super interested, but the "get started" options to install are a bit beyond my knowledge.
> 
> Is there any way to spin a container image using docker?

Hello!

Thank you for contacting me, I'm glad to hear about your interest in YAFFA. At the moment, there's no Docker image available as an installation option, but it is on the to-do list. I'll provide you with an update, when it becomes available. In the meantime, is there any specific part of the installation guide, which could be enhanced to help you get started?

**Reply by LukanRocks** [reply]
Hey, thank you so much for the fast response!

I guess I will wait for the container image, but I appreciate the help. As I mentioned, because I don't have the technical background, installing things through the container gives me that "easy" spin up and down in a controlled environment that gives me confidence that I won't mess things up or leave stuff around, you know? It's a peace of mind thing.

But if there is anything I can do to help the project get there, I would gladly do it. You guys are taking contributions?

**Reply by kantorge** [reply]
Sure, I'll keep you updated.

There's no predefined contribution guide yet for this repository, but otherwise, any contribution is welcome. Let me know if you have anything on your mind. Testing the Docker deployment will be highly appreciated.

**Reply by kantorge** [reply]
@lukanvanderlinde , I have just created a first version of the Docker image for YAFFA. It is published to [DockerHub](https://hub.docker.com/r/kantorge/yaffa), and I created an [installation instructions page](https://www.yaffa.cc/documentation/resources/getting-started/installation/install-yaffa-using-docker-for-windows/) for it. I hope you'll be able to give it a try, and I'm open to hearing back any of your feedback.

**Reply by LukanRocks** [reply]
Hey Kantorge, sorry for the delay; I didn't saw this reply notification. I'm happy to hear the updates! I will start testing today.

**Reply by LukanRocks** [reply]
Hey @kantorge, I've tried to setup but without success so far. I've tried to run on my intel nuc where I usually have my services running.
 
First issue happened right away after starting from the compose and .env files available. I got the following error:
```
app-1        | In Connection.php line 829:
app-1        |                                                                                
app-1        |   SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select t  
app-1        |   able_name as `name`, (data_length + index_length) as `size`, table_comment   
app-1        |   as `comment`, engine as `engine`, table_collation as `collation` from infor  
app-1        |   mation_schema.tables where table_schema = 'yaffa_db' and table_type in ('BA  
app-1        |   SE TABLE', 'SYSTEM VERSIONED') order by table_name)                          
app-1        |                                                                                
app-1        | 
app-1        | In Connector.php line 65:
app-1        |                                              
app-1        |   SQLSTATE[HY000] [2002] Connection refused  
app-1        |                                              
app-1        | 
app-1 exited with code 1
```

I was able to progress by specifying a subnet for the yaffa network:
```
networks:
  yaffa-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
```
        
and specifically setting a IP for the db:
```
db:
    image: mysql/mysql-server:8.0
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - $DOCKER_DATA_DIR/yaffa/db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      yaffa-network:
        ipv4_address: 172.18.0.102 # fixed ip to be easily targeted
```

To allow me to directly set DB_HOST=172.18.0.102 in the env file.

With those changes I was able to a fully initiate the app, but when accessing through the browser I received a 500 server error from the application.
<img width="581" alt="Screenshot 2025-01-29 at 23 37 36" src="https://github.com/user-attachments/assets/dbd6085c-427e-425e-a24d-f14061f41ca7" />
The UI leads me to believe the app is running but is refusing my connection. The logs only show a connection request going to the app, but nothing else to explain what is going wrong.
