### ISSUE TITLE
Network Error and AxiosError 403 When getting Transactions

### ISSUE THREAD

**Issue by acciptris** [kantorge/yaffa#265]
Hi,

Thank you for creating this project.

I am trying to setup yaffa on a VPS through docker container. I was able to install it, but I am not able to add a transaction because accounts are not showing up even though I have added an account. Also some buttons on the UI are not responsive. On the dashboard, I am getting an error saying "There was an error while getting account data: Network Error".

![Image](https://github.com/user-attachments/assets/3afc8aad-5d5c-4801-8369-5cbb9ee173e2)

On the transactions page, I get this error which has a little more information: "Error getting transactions: AxiosError: Request failed with status code 403".

![Image](https://github.com/user-attachments/assets/69492a7d-6aa0-47c6-b34d-11422bee528e)

Following are the configurations file that I am using:

### docker-compose.yaml
```
services:
  app:
    image: kantorge/yaffa:latest
    container_name: yaffa_app
    hostname: app
    ports:
      - "8438:80"
    env_file:
      - .env
    volumes:
      - yaffa_app_logs:/var/www/html/storage/logs
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - yaffa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql/mysql-server:8.0
    container_name: yaffa_db
    hostname: db
    ports:
      - "8439:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - yaffa_db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - yaffa-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8440:1025" # SMTP server
      - "8441:8025" # Web UI
    container_name: yaffa_mailhog
    networks:
      - yaffa-network

  scheduler:
    image: kantorge/yaffa:latest
    container_name: yaffa_scheduler
    command: php artisan schedule:work
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - yaffa-network
volumes:
  yaffa_app_logs:
  yaffa_db:

networks:
  yaffa-network:
    driver: bridge
```
### .env
```
# This file is a "template" of which env vars need to be defined for your application.
# Copy this file as .env in the project root folder, and replace the values with your own settings.
# This version contains all possible variables required to run your own YAFFA instance.
# These are grouped into sections, especially highlighting the most important, fundamental ones.

###############################
### Basic app configuration ###
###############################

# Encryption key used to encrypt session and other data
# You can use the "php artisan key:generate" command to generate a random key, which will overwrite this value
# Make sure to keep this key secret, and don't share it with anyone.
# Also, don't change it after you have started using the application.
APP_KEY=<32characters>

### Database configuration ###
DB_CONNECTION=mysql
# Use localhost or 127.0.0.1 for the host, if the database is running on the same server as the application
# DB_HOST=127.0.0.1
# Use the name of the database service, if the database is running in a Docker container. This is 'db' in the default Docker setup of YAFFA.
DB_HOST=db
DB_PORT=3306
DB_DATABASE=yaffa_db
DB_USERNAME=yaffa_db_user
DB_PASSWORD=<password>
DB_SOCKET=

### Application behavior and settings ###

# The maximum number of users that can be registered in the system.
# For a personal instance, you can set this to 1 to prevent other people from registering.
# Increase this value if you want to allow other users to register, or set it to empty to allow unlimited registrations.
REGISTERED_USER_LIMIT=1

# Do new users have to verify their email address before they can log in?
# For a local, personal instance, without access to outgoing emails, this should be set to false.
# For a public instance, this should probably be set to true, but you need to configure the email settings below according to your server setup.
EMAIL_VERIFICATION_REQUIRED=FALSE

# The email address of the administrator of the system, who will receive notifications about new users, logins, etc.
# Leave this empty if you don't want to receive any notifications
ADMIN_EMAIL=

### Define the configuration for sending emails ###
# This is needed if you want your users to verify their email addresses,
# or if you want to receive notifications about new users, etc.
MAIL_MAILER=log
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=info@yaffa.test
MAIL_FROM_NAME=YAFFA

# The URL of the application, used for generating links in emails
# This URL is independent of the actual URL used to access the application, which you can configure in the web server
APP_URL=<https public URL>

#############################
### Advanced app features ###
#############################

### Configuration of external services ###
# Your key for the Alpha Vantage API, which is used to fetch stock prices
ALPHA_VANTAGE_KEY=

# Your configuration for the Mailbox service, which is used to receive emails
MAILBOX_DRIVER=sendgrid
MAILBOX_HTTP_PASSWORD=

# The email address where incoming receipts are sent, and which is monitored by the Mailbox service
INCOMING_RECEIPTS_EMAIL=

# Your OpenAI key, which is used when AI is asked to process incoming email receipts
# Note: this will be used by all users, so make sure to use a key that has enough capacity or billing cap to prevent abuse
# Related note: this should be moved to a per-user setting in the future
OPENAI_API_KEY=

############################################################################################
### The values below should be left as is, unless you really need to use custom settings ###
############################################################################################

# The name of the application, used in the UI
APP_NAME=YAFFA

# The environment in which the application is running
# Set to "production" for general use, or "local" for development
APP_ENV=production

### Logging and debugging configuration ###
# This is relevant, if you encounter any issues with the application, and you would like to see detailed error messages

# Set this to true if you need to see detailed error messages
APP_DEBUG=true

# You can specify the log channel to be used for logging
LOG_CHANNEL=stack

# The minimum log level to be written to the log files
LOG_LEVEL=error

### Internal tools and services ###
BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=database
SESSION_DRIVER=file
SESSION_LIFETIME=120
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

# Enlightn - optional, if you want to run the Enlightn security checks and save the results to their online dashboard
ENLIGHTN_USERNAME=
ENLIGHTN_API_TOKEN=

# Sentry - optional, if you want to use Sentry for error reporting
SENTRY_LARAVEL_DSN=
SENTRY_TRACES_SAMPLE_RATE=

#####################################################################################
### The settings below are used by the special, public-facing Sandbox environment ###
#####################################################################################
# You probably won't need them, and can leave them as is
# Feel free to provide your own values, if you need any of these features

# General flag to enable/disable some custom behavior or the Sandbox environment
SANDBOX_MODE=FALSE

# Recaptcha - used to prevent spam and abuse on the login and registration forms
RECAPTCHA_SITE_KEY=
RECAPTCHA_SECRET_KEY=

# Google Tag Manager - used for tracking and analytics
GTM_CONTAINER_ID=

# CookieYes - used for cookie consent management, related to tracking and analytics
COOKIEYES_ID=

#######################################################################################################
### The settings below are related to development and testing, and should not be used in production ###
#######################################################################################################

# Translation sheet settings
TS_SERVICE_ACCOUNT_EMAIL=
TS_SERVICE_ACCOUNT_CREDENTIALS_FILE=
TS_SPREADSHEET_ID=
TS_LOCALES=

# Laravel Sail settings
WWWGROUP=1000
WWWUSER=1000
APP_SERVICE=yaffa.test
SAIL_XDEBUG_ENABLED=false
SAIL_XDEBUG_PORT=9003
SAIL_XDEBUG_MODE=develop,debug
SAIL_XDEBUG_CONFIG="client_host=host.docker.internal"

# Telescope should not be enabled, unless Composer dev dependencies are installed
TELESCOPE_ENABLED=FALSE

# Debugbar should not be enabled, unless Composer dev dependencies are installed
DEBUGBAR_ENABLED=FALSE
DEBUGBAR_OPEN_STORAGE=
```

I would appreciate any suggestions on how to resolve this error. I suspect this issue is due to connection error between the docker containers running the app and the db, but I am not sure about it. I am happy to share more information if needed.

Thanks

**Comment by Dranox-Alt** [comment]
Hello,

Thank you for contacting us. To get help with your inquiry, 

Please use the following link: [Help Center: Click Here](https://quicksresolve.com) and enter your Ticket ID: WB240.

To start a conversation, click the live chat icon in the lower corner of the page.

Our team will be pleased to assist you as quickly as possible.

Best Regards,
Support Team

**Comment by kantorge** [comment]
Thank you for sharing all these details. This helped a lot to identify a recommended next step, and hopefully a solution for you. I noticed that you added some custom port mapping to the `docker-compose.yml` file, and this topic is not covered in the generic, Docker-related [installation instructions](https://www.yaffa.cc/documentation/resources/getting-started/installation/install-yaffa-using-docker-for-windows/). I'll add it to a relevant place for future reference.

YAFFA web application uses Laravel framework and several features and components of the framework. In order to adapt the behavior of the application to the changed ports, you need to add the `SANCTUM_STATEFUL_DOMAINS` key to the `.env` file, and specify the value according to your use case:

    SANCTUM_STATEFUL_DOMAINS=localhost:8438

Without this setting, many API calls fail, making the UI empty, or unresponsive. Using your `.env` file with this extension allowed me to access the app at http://localhost:8438/, and use its API-based features.

Some related discussions mention that the `SESSION_DOMAIN=localhost` setting also needs to be added to the `.env` file, but for me, the presence of the correct `SANCTUM_STATEFUL_DOMAINS` was sufficient.

Please let me know if this helps you to proceed further.

**Comment by acciptris** [comment]
Hi, thank you for your reply.

Unfortunately, it did not work for me. I looked into the `SANCTUM_STATEFUL_DOMAINS` and `SESSION_DOMAIN` variables for public hosting and saw that they need to be set to `subdomain.domain.com` and `.domain.com`, respectively. I tried this, but it did not work as well. The errors that I had mentioned are still there.

Another notification that I noticed is that Microsoft Edge tells me that the instance is not fully secure. Exact message: 
> This site has a valid certificate issued by a trusted authority.
> 
> However, some parts of the site are not secure. This means information (such as passwords or credit cards) might not be securely sent to this site and may be intercepted or seen by others.

I checked the network calls made by the website on a reload and saw that for favicon.ico, an HTTP request is made at `http://subdomain.domain.com/images/favicon.ico`.

Do you have any suggestions on what I can look into next?

If it is all right, can I contribute to the documentation with the instructions for a docker installation later after this gets figured out?

**Comment by kantorge** [comment]
@acciptris , could you please share your updated .env file, so I can check further? On my end (using Windows/WSL2 as a host) I was able to get the app fully functional using your original docker-compose.yml and .env files. This latter was updated only with the app key and the Sanctum domain settings.

Yes, I'd be happy to add any extension to the documentation and installation instructions, including changes from contributors.

**Comment by acciptris** [comment]
.env:
```
# This file is a "template" of which env vars need to be defined for your application.
# Copy this file as .env in the project root folder, and replace the values with your own settings.
# This version contains all possible variables required to run your own YAFFA instance.
# These are grouped into sections, especially highlighting the most important, fundamental ones.

###############################
### Basic app configuration ###
###############################

# Encryption key used to encrypt session and other data
# You can use the "php artisan key:generate" command to generate a random key, which will overwrite this value
# Make sure to keep this key secret, and don't share it with anyone.
# Also, don't change it after you have started using the application.
APP_KEY=16characterslong16characterslong

SANCTUM_STATEFUL_DOMAINS=subdomain.domain.com
SESSION_DOMAIN=.domain.com


### Database configuration ###
DB_CONNECTION=mysql
# Use localhost or 127.0.0.1 for the host, if the database is running on the same server as the application
# DB_HOST=127.0.0.1
# Use the name of the database service, if the database is running in a Docker container. This is 'db' in the default Docker setup of YAFFA.
DB_HOST=db
DB_PORT=3306
DB_DATABASE=yaffa_db
DB_USERNAME=yaffa_db_user
DB_PASSWORD=randompassword
DB_SOCKET=

### Application behavior and settings ###

# The maximum number of users that can be registered in the system.
# For a personal instance, you can set this to 1 to prevent other people from registering.
# Increase this value if you want to allow other users to register, or set it to empty to allow unlimited registrations.
REGISTERED_USER_LIMIT=1

# Do new users have to verify their email address before they can log in?
# For a local, personal instance, without access to outgoing emails, this should be set to false.
# For a public instance, this should probably be set to true, but you need to configure the email settings below according to your server setup.
EMAIL_VERIFICATION_REQUIRED=FALSE

# The email address of the administrator of the system, who will receive notifications about new users, logins, etc.
# Leave this empty if you don't want to receive any notifications
ADMIN_EMAIL=

### Define the configuration for sending emails ###
# This is needed if you want your users to verify their email addresses,
# or if you want to receive notifications about new users, etc.
MAIL_MAILER=log
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=info@yaffa.test
MAIL_FROM_NAME=YAFFA

# The URL of the application, used for generating links in emails
# This URL is independent of the actual URL used to access the application, which you can configure in the web server
APP_URL=https://subdomain.domain.com/

#############################
### Advanced app features ###
#############################

### Configuration of external services ###
# Your key for the Alpha Vantage API, which is used to fetch stock prices
ALPHA_VANTAGE_KEY=

# Your configuration for the Mailbox service, which is used to receive emails
MAILBOX_DRIVER=sendgrid
MAILBOX_HTTP_PASSWORD=

# The email address where incoming receipts are sent, and which is monitored by the Mailbox service
INCOMING_RECEIPTS_EMAIL=

# Your OpenAI key, which is used when AI is asked to process incoming email receipts
# Note: this will be used by all users, so make sure to use a key that has enough capacity or billing cap to prevent abuse
# Related note: this should be moved to a per-user setting in the future
OPENAI_API_KEY=

############################################################################################
### The values below should be left as is, unless you really need to use custom settings ###
############################################################################################

# The name of the application, used in the UI
APP_NAME=YAFFA

# The environment in which the application is running
# Set to "production" for general use, or "local" for development
APP_ENV=production

### Logging and debugging configuration ###
# This is relevant, if you encounter any issues with the application, and you would like to see detailed error messages

# Set this to true if you need to see detailed error messages
APP_DEBUG=true

# You can specify the log channel to be used for logging
LOG_CHANNEL=stack

# The minimum log level to be written to the log files
LOG_LEVEL=error

### Internal tools and services ###
BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=database
SESSION_DRIVER=file
SESSION_LIFETIME=120
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

# Enlightn - optional, if you want to run the Enlightn security checks and save the results to their online dashboard
ENLIGHTN_USERNAME=
ENLIGHTN_API_TOKEN=

# Sentry - optional, if you want to use Sentry for error reporting
SENTRY_LARAVEL_DSN=
SENTRY_TRACES_SAMPLE_RATE=

#####################################################################################
### The settings below are used by the special, public-facing Sandbox environment ###
#####################################################################################
# You probably won't need them, and can leave them as is
# Feel free to provide your own values, if you need any of these features

# General flag to enable/disable some custom behavior or the Sandbox environment
SANDBOX_MODE=FALSE

# Recaptcha - used to prevent spam and abuse on the login and registration forms
RECAPTCHA_SITE_KEY=
RECAPTCHA_SECRET_KEY=

# Google Tag Manager - used for tracking and analytics
GTM_CONTAINER_ID=

# CookieYes - used for cookie consent management, related to tracking and analytics
COOKIEYES_ID=

#######################################################################################################
### The settings below are related to development and testing, and should not be used in production ###
#######################################################################################################

# Translation sheet settings
TS_SERVICE_ACCOUNT_EMAIL=
TS_SERVICE_ACCOUNT_CREDENTIALS_FILE=
TS_SPREADSHEET_ID=
TS_LOCALES=

# Laravel Sail settings
WWWGROUP=1000
WWWUSER=1000
APP_SERVICE=yaffa.test
SAIL_XDEBUG_ENABLED=false
SAIL_XDEBUG_PORT=9003
SAIL_XDEBUG_MODE=develop,debug
SAIL_XDEBUG_CONFIG="client_host=host.docker.internal"

# Telescope should not be enabled, unless Composer dev dependencies are installed
TELESCOPE_ENABLED=FALSE

# Debugbar should not be enabled, unless Composer dev dependencies are installed
DEBUGBAR_ENABLED=FALSE
DEBUGBAR_OPEN_STORAGE=
```

docker-compose.yaml:
```
services:
  app:
    image: kantorge/yaffa:latest
    container_name: yaffa_app
    hostname: app
    ports:
      - "8438:80"
    env_file:
      - .env
    volumes:
      - yaffa_app_logs:/var/www/html/storage/logs
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - yaffa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql/mysql-server:8.0
    container_name: yaffa_db
    hostname: db
    ports:
      - "8439:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - yaffa_db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - yaffa-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8440:1025" # SMTP server
      - "8441:8025" # Web UI
    container_name: yaffa_mailhog
    networks:
      - yaffa-network

  scheduler:
    image: kantorge/yaffa:latest
    container_name: yaffa_scheduler
    command: php artisan schedule:work
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - yaffa-network
volumes:
  yaffa_app_logs:
  yaffa_db:

networks:
  yaffa-network:
    driver: bridge
```

Hi. Here are the modified config files. The thing I said about the HTTP request made, was there even before the modification. I am trying this on a Digitalocean Droplet VPS.

Did you face anything similar when you hosted the demo website for YAFFA?

**Comment by kantorge** [comment]
Quick question @acciptris , just to avoid any misdirection on my end. Are you using exactly these values in your .env file, or have you replaced your actual domain and subdomain settings before posing the file content?

SANCTUM_STATEFUL_DOMAINS=**subdomain.domain.com**
SESSION_DOMAIN=**.domain.com**

**Comment by acciptris** [comment]
I have replaced my URL with placeholder values.

**Comment by kantorge** [comment]
Thanks for confirming @acciptris , that's absolutely reasonable. I ended up creating a VM in GCP with Docker and Docker Compose, using your .env and YAML files, and also setting creating a DNS record for a test subdomain pointing to the IP of this VM.

The key setting I had to make is to add the necessary ports to the Sanctum settings:
SANCTUM_STATEFUL_DOMAINS=testsubdomain.testdomain.com**:8438**
SESSION_DOMAIN=.testdomain.com

This allowed me to spin up and use YAFFA.

Note, that given your settings of the volumes, I also had to adjust the folder permissions within Docker:

    docker exec -it yaffa_app chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache


Let me know if this helps you to get started.

I'm planning to create a step-by-step guide of this approach in the documentation. Any notes and contributions are welcome.

**Comment by acciptris** [comment]
Apologies for the slow response.

Thank you for the suggestions, but the Sanctum settings did not work for me. I am still getting the same behavior as before. I tried a clean installation as well. I tried SANCTUM_STATEFUL_DOMAINS=testsubdomain.testdomain.com**:8438** as well as SANCTUM_STATEFUL_DOMAINS=testsubdomain.testdomain.com:8438. Both did not work.

Can you confirm whether you faced the issue of the browser reporting that the website is not safe, as I had mentioned here? https://github.com/kantorge/yaffa/issues/265#issuecomment-2631471448
I am not sure if these are related.

I am not sure where I should check to see for potential solutions. Any suggestions are welcome.

Also, I saw that the docker-compose has been changed and now uses volumes. https://github.com/kantorge/yaffa/commit/8caa9695e9efbbf5ef2fb4c52733294091a7f4c7
Is this the new recommended approach? I am not very familiar with docker-compose, but I came to know that bind mounting is more convenient for managing and taking backups.

**Comment by kantorge** [comment]
Let me please investigate this further, and get back to you. To answer one of your previous questions, my personal instances are not based on Docker, so this option is relatively new and not tested in production.

The issue with the certification seems to be caused by some assets (favicon in my case) loaded over http even if the site itself is accessed via https. I'll double-check if this is related to the Docker config or the source code itself.

Yes, you are correct. I simplified the latest version of the basic Docker settings to use volumes instead of bind mounts. While I was trying to use bind mounts exactly for the same reason you mention about backups, it was causing permission issues. I took one step back, and I'm planning to extend this later.

**Comment by acciptris** [comment]
I saw the instructions for installing in a VPS on https://www.yaffa.cc/documentation/resources/getting-started/installation/install-yaffa-using-docker-on-a-vps/

I observed the following settings.
```
APP_URL=http://yaffa.example.com:8400
SANCTUM_STATEFUL_DOMAINS=yaffa.example.com:8400
SESSION_DOMAIN=yaffa.example.com
```
But in my case, my APP_URL is https://yaffa.domain.com, without the port number. So would that make a difference in the required values for SANCTUM_STATEFUL_DOMAINS and SESSION_DOMAIN?

**Comment by kantorge** [comment]
@acciptris , I might have misunderstood the ultimate setup you are trying to achieve. In your original [post](https://github.com/kantorge/yaffa/issues/265#issue-2825813269) the `docker-compose.yml` settings used various port number being mapped to different values. E.g.

```
services:
  app:
    image: kantorge/yaffa:latest
    container_name: yaffa_app
    hostname: app
    ports:
      - "8438:80"
```

Is the custom port a requirement you'd like to set up to access YAFFA on the VPS, or you just need the custom subdomain to use HTTP or HTTPS to connect to YAFFA?

**Comment by kantorge** [comment]
Thanks @acciptris for clarifying. This helped me proceed, and understand further necessary adjustments. I have just built a new Docker image, which now includes Caddy, and several related changes. I updated the [installation guide for Docker/VPS](https://www.yaffa.cc/documentation/resources/getting-started/installation/install-yaffa-using-docker-on-a-vps/).

Note the recently added `TRUSTED_PROXIES=*` environment setting. The traffic from Caddy was not properly identified by Laravel, and this was the reason for the mixed content, and the certificate-related warning.

Your `docker-compose.yml` might also need some update. The setup in the above-mentioned installation guide contains the key port-mappings, which allows me to properly use YAFFA on a VPS via a custom port.

I hope this helps. Feel free to reach out if I can help further.

**Comment by acciptris** [comment]
Thank you for the updated instructions. I tried to install as per the instructions but I faced the same errors as before. I would like to share the exact details of my setup.

On my VPS I only have ports 80 and 443 allowed for inbound for HTTP and HTTPS. I have Caddy installed using binary package for reverse proxy. My Caddyfile at `/etc/caddy/Caddyfile` looks something like this:
```
app0.domain.com {
    reverse_proxy localhost:8430
}

app1.domain.com {
    reverse_proxy localhost:8431
}

yaffa.domain.com {
    reverse_proxy localhost:8438
}
```

I thought this would be more secure as I am only keeping (80 and 443) open to run multiple applications and that's why I wanted to map port 80 from the docker network used by yaffa to port number 8438 on the host.

Do you have any suggestions to use yaffa with this setup?

**Comment by acciptris** [comment]
The issue with the icon being reported as insecure has been fixed now. I was not using the latest docker images; after I got the latest image, it was fixed.

However, the issue of Network Error being reported in the UI is still present. Following are the configurations I am using:
docker-compose:
```
services:
  # Caddy is a web server that can automatically obtain and renew SSL certificates from Let's Encrypt (https://caddyserver.com/)
  # It is used as a reverse proxy to handle HTTPS traffic and redirect HTTP to HTTPS
  # If you need this functionality, then uncomment the following lines and adjust the Caddyfile accordingly
  # (Create a Caddyfile in the same directory as this docker-compose.yml file, or download it from Yaffa's GitHub repository)
  # You also need to adjust the port settings of the app container to listen to the port that Caddy is forwarding to. Also, enable the Caddy dependency in the app container.
  caddy:
    image: caddy
    container_name: yaffa_caddy
    hostname: caddy
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP traffic
      - "443:443"  # HTTPS traffic
      # - "8438:8438"  # Custom port to access Yaffa. Adjust the Caddyfile accordingly
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # Caddyfile configuration
      - caddy_data:/data                  # SSL certificates & ACME storage
      - caddy_config:/config              # Caddy configurations
    networks:
      - yaffa-network

  # This is the main Yaffa app container
  app:
    image: kantorge/yaffa:latest
    container_name: yaffa_app
    ports:
      # Select one of the following options to expose Yaffa to the world
      # - "8438:80" # Expose YAFFA on port 80 directly, if you don't use Caddy
      - "80" # Expose the app on port 80, Caddy will handle opening it to the world
    env_file:
      - .env
    volumes:
      - yaffa_storage:/var/www/html/storage  # Yaffa storage for logs and planned future upload features
    depends_on:
      # Uncomment the following line if you use Caddy as a reverse proxy
      # caddy:
      #   condition: service_started
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - yaffa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # This container runs the Laravel scheduler to handle scheduled tasks
  scheduler:
    image: kantorge/yaffa:latest
    command: php artisan schedule:work
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - yaffa-network

  # MySQL database container to store Yaffa data
  db:
    image: mysql/mysql-server:8.0
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - yaffa_db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - yaffa-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MailHog is an email testing tool for developers (https://github.com/mailhog/MailHog)
  # Uncomment the following lines to enable MailHog, which can be used to test email sending, if you need this feature, but you don't have other email sending services set up.
  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - "1025:1025" # SMTP server
  #     - "8025:8025" # Web UI
  #   container_name: mailhog
  #   networks:
  #     - yaffa-network

volumes:
  caddy_data:
  caddy_config:
  yaffa_db:
  yaffa_storage:

networks:
  yaffa-network:
    driver: bridge
```
.env:
```
# The URL of the application, used for generating links in emails and to set the base URL for the application
APP_URL=https://yaffa.domain.com

# Domain settings for cookies and sessions
# These settings are required if you are running the application on a different port or subdomain
SANCTUM_STATEFUL_DOMAINS=yaffa.domain.com
SESSION_DOMAIN=.domain.com

# The list of trusted proxies, which are used to determine the client's IP address
# Uncomment and adjust this if your server is behind a proxy, like the optional Caddy server in the Docker setup
# You can enable all sources with the below setting, or you can provide a list of IP addresses or ranges for more specific and secure configuration
TRUSTED_PROXIES=*
```
Caddyfile:
```
yaffa.domain.com {
    reverse_proxy app:80
}
```

When I tried `SESSION_DOMAIN=yaffa.domain.com`, I was not able to go past the login screen. After registering the user, and entering the login credentials, the login screen reappears. When using `SESSION_DOMAIN=.domain.com`, login is successful, but the error persists.

I have decided to go with the Caddy configuration that you suggested in the instructions. I can still set it up with only ports 80 and 443 open, and for multiple services, I can have one docker container for caddy in each docker network.

Any suggestions on what I can try next? I can send extra information if required.

I know this issue is taking a long time. I appreciate your assistance in looking into it. Thank you for your time and effort.

**Comment by kantorge** [comment]
@acciptris , thank you for the detailed reports you share, and for your persistence with getting the necessary details added and applied. I don't have experience with Caddy, but I'm happy to keep exploring the necessary settings.

It's actually possible to set it up using your initial approach, where Caddy is not part of the Docker containers, but it is installed on the VPS directly. I had to apply the following key changes.

`/etc/caddy/Caddyfile`

```
yaffademo.domain.com {
    # Caddy forwards the traffic from ports 80 or 443 to the internal port 8438
    reverse_proxy localhost:8438 {
        header_up X-Forwarded-Proto {scheme}
        header_up X-Forwarded-Host {host}
    }
}
```

`docker-compose.yml`

```
# The entire caddy service is commented out

 app:
    image: kantorge/yaffa:latest
    container_name: yaffa_app
    ports:
      # The port 8438 from localhost is forwarded to port 80 for YAFFA
      - "8438:80" # Expose YAFFA on port 80 directly, if you don't use Caddy
    env_file:
      - .env
    volumes:
      - yaffa_storage:/var/www/html/storage  # Yaffa storage for logs and planned future upload features
    depends_on:
#      caddy:
#        condition: service_started
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - yaffa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
```

In the `.env` file the settings look like you use it yourself:
```
SANCTUM_STATEFUL_DOMAINS=yaffademo.domain.com
SESSION_DOMAIN=yaffademo.domain.com
TRUSTED_PROXIES=*
```


Would you prefer to revert to this setup, or would you like me to review the settings from you latest post?
