### ISSUE TITLE
MySQL Connection Refused using supplied docker compose and .env

### ISSUE THREAD

**Issue by electricmessiah** [kantorge/yaffa#301]
```
In Connection.php line 829:

                                                                               

  SQLSTATE[HY000] [2002] Connection refused (Connection: mysql, SQL: select t  

  able_name as `name`, (data_length + index_length) as `size`, table_comment   

  as `comment`, engine as `engine`, table_collation as `collation` from infor  

  mation_schema.tables where table_schema = 'yaffa_db' and table_type in ('BA  

  SE TABLE', 'SYSTEM VERSIONED') order by table_name)                          

                                                                               

In Connector.php line 65:

                                             

  SQLSTATE[HY000] [2002] Connection refused  
```

**Comment by kantorge** [comment]
Could you please provide a bit more context? How your `docker-compose.yml` and `.env` files look like (without the passwords and any other sensitive information)?

**Comment by electricmessiah** [comment]
DB_HOST is set to `db`

**Comment by kantorge** [comment]
Thanks for checking, this rules out a possible configuration issue. Additionally, I found the likely root-cause of the issue you are facing. I was able to setup YAFFA via Docker and Portainer.

In the Portainer stack configuration you commented the reference to the `.env` file, as you provide all the configuration values on the Portainer interface. (Via uploading the file, which is converted to a list of key-value pairs.) However, this is [claimed to be one of the undocumented](https://www.portainer.io/blog/using-env-files-in-stacks-with-portainer) features of Portainer Stacks, as in practice the values get loaded into the containers via a `stack.env` file. Thus, the reason for the connection error is that the app and scheduler containers don't have the database (and any other settings) configured. To make this work, you need to enable the `env_file` setting and adjust accordingly, for both the `app` and `scheduler` containers:

```
    env_file:
      - stack.env
````

Using this approach, and assuming the `DB_PORT` being 3306, this needs to be used in the Docker configuration, too. Note, that you'll need to provide the `APP_KEY` environmental variable manually via Portainer.

Let me know if this allows you to setup and access YAFFA using Portainer.

**Comment by electricmessiah** [comment]
I added the env_file lines which produced this error.

```In Connection.php line 829:

                                                                               

  SQLSTATE[HY000] [1045] Access denied for user 'yaffa_user'@'192.168.32.4' (  

  using password: YES) (Connection: mysql, SQL: select table_name as `name`,   

  (data_length + index_length) as `size`, table_comment as `comment`, engine   

  as `engine`, table_collation as `collation` from information_schema.tables   

  where table_schema = 'yaffa_db' and table_type in ('BASE TABLE', 'SYSTEM VE  

  RSIONED') order by table_name)                                               

                                                                               

In Connector.php line 65:

                                                                               

  SQLSTATE[HY000] [1045] Access denied for user 'yaffa_user'@'192.168.32.4' (  

  using password: YES)         ```

**Comment by kantorge** [comment]
Have you recreated the containers with any settings you changed? Please share your YAML and environment settings, that would be needed to understand the root cause. 

For your reference, this is a working setup using Portainer Stacks. I customized the service and container names to avoid conflicts with other test assets, but it's otherwise based on the standard YML file from the repository.

```
services:
  app_301:
    image: kantorge/yaffa:latest
    container_name: yaffa_app_301
    ports:
      - "8088:80"  # Changed external port to avoid conflict with other test instances on the same server
    env_file:
      - stack.env  
    environment:
      RUNS_SCHEDULER: FALSE
    volumes:
      - yaffa_storage_301:/var/www/html/storage
    depends_on:
      db_301:
        condition: service_healthy
      redis_301:
        condition: service_started
    restart: unless-stopped
    networks:
      - yaffa-network-301
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  scheduler_301:
    image: kantorge/yaffa:latest
    container_name: yaffa_scheduler_301
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
    env_file:
      - stack.env
    environment:
      RUNS_SCHEDULER: TRUE
    depends_on:
      db_301:
        condition: service_healthy
      redis_301:
        condition: service_started
    restart: unless-stopped
    networks:
      - yaffa-network-301

  redis_301:
    image: redis:alpine
    container_name: yaffa_redis_301
    restart: unless-stopped
    networks:
      - yaffa-network-301

  db_301:
    image: mysql/mysql-server:8.0
    ports:
      - "3310:3306"  # Unique host port to avoid conflict with other test instances on the same server
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - yaffa_db_301:/var/lib/mysql
    restart: unless-stopped
    networks:
      - yaffa-network-301
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  yaffa_db_301:
  yaffa_storage_301:

networks:
  yaffa-network-301:
    driver: bridge
```

Environment variables:
```
APP_KEY=[REDACTED, BUT JUST A 32 BYTES BASE64 STRING]
DB_CONNECTION=mysql
DB_HOST=db_301
DB_PORT=3306
DB_DATABASE=yaffa_db
DB_USERNAME=yaffa_user
DB_PASSWORD=yaffa_password
DB_SOCKET=
REGISTERED_USER_LIMIT=1
EMAIL_VERIFICATION_REQUIRED=FALSE
ADMIN_EMAIL=
MAIL_MAILER=log
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=info@yaffa.test
MAIL_FROM_NAME=YAFFA
APP_URL=http://yaffa.local:8088
TRUSTED_PROXIES=*
ALPHA_VANTAGE_KEY=
MAILBOX_DRIVER=sendgrid
MAILBOX_HTTP_PASSWORD=
INCOMING_RECEIPTS_EMAIL=
OPENAI_API_KEY=
APP_NAME=YAFFA
APP_ENV=production
APP_DEBUG=false
LOG_CHANNEL=stack
LOG_LEVEL=error
BROADCAST_DRIVER=log
CACHE_DRIVER=redis
QUEUE_CONNECTION=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=120
REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379
RUNS_SCHEDULER=TRUE
ENLIGHTN_USERNAME=
ENLIGHTN_API_TOKEN=
SENTRY_LARAVEL_DSN=
SENTRY_TRACES_SAMPLE_RATE=
SANDBOX_MODE=FALSE
RECAPTCHA_SITE_KEY=
RECAPTCHA_SECRET_KEY=
GTM_CONTAINER_ID=
COOKIEYES_ID=
TS_SERVICE_ACCOUNT_EMAIL=
TS_SERVICE_ACCOUNT_CREDENTIALS_FILE=
TS_SPREADSHEET_ID=
TS_LOCALES=
WWWGROUP=1000
WWWUSER=1000
APP_SERVICE=yaffa.test
SAIL_XDEBUG_ENABLED=false
SAIL_XDEBUG_PORT=9003
SAIL_XDEBUG_MODE=develop,debug
SAIL_XDEBUG_CONFIG="client_host=host.docker.internal"
SERVER_NAME=yaffa.test
SSL_DOMAIN=yaffa.test
TELESCOPE_ENABLED=FALSE
DEBUGBAR_ENABLED=FALSE
DEBUGBAR_OPEN_STORAGE=
```
